Menu details
Symphono/wfl pull request #25
Opened 2017-07-05 21:21 UTC by TNagaraja

Issue #20

2017-07-06 17:30 UTC, JChapman202 requested changes
We're heading down the right path.  We'll want to do some refactoring that we can do in the next PR, but in this one I would like you to remove the Id Check method for Restaurant.

2017-07-06 17:30 UTC, JChapman202 commented on wfl/Controllers/RestaurantsController.cs
> +            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(restaurant?.Name) || (restaurant.MenuLink != null && !Uri.IsWellFormedUriString(restaurant.MenuLink.ToString(), UriKind.Absolute)))
I think this is good for now, but I think we're also starting to see how handling validation in this manner starts to get verbose and repetitive across methods.  Perhaps there are some strategies we can think of for future enhancement that may reduce the duplication and verboseness.  I have some thoughts we can discuss further at another time.

2017-07-06 17:30 UTC, JChapman202 commented on wfl/Database/IDBManager.cs
> +        Task<RestaurantDto> GetRestaurantWithIdAsync(string Id);
I don't actually think it makes sense to use a RestaurantDto in this manner.  I realize some of us may not be on the same page, and that may be causing some confusion.  Sorry about that!  Once we return a RestaurantDto it defeats the purpose of some of the benefits we were going with to post a RestaurantDto (like not being able to provide an Id).  I'm good with this for now, but we should spend more time discussing potential alternatives.

I think once we discuss alternatives to `IDBManager` it'll make things a bit clearer for us.

2017-07-06 17:30 UTC, JChapman202 commented on wfl/Database/MongoDBManager.cs
> +        public async Task<bool> CheckRestaurantIdAsync(string id)
Why do we need to check a restaurant id?  One key thing to think through when writing code is to simplify your interfaces.  If you can use the same interface for 2 purposes, then you absolutely should do it.  It'll make your API simpler to consume and re-use.  So in this case, could we instead use the Get method, and when it returns null you know there is no item at that id?  Then we can offer a single interface and still solve all use cases.

2017-07-06 17:35 UTC, TNagaraja commented on wfl/Controllers/RestaurantsController.cs
> +            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(restaurant?.Name) || (restaurant.MenuLink != null && !Uri.IsWellFormedUriString(restaurant.MenuLink.ToString(), UriKind.Absolute)))
Sounds good.

2017-07-06 17:38 UTC, TNagaraja commented on wfl/Database/IDBManager.cs
> +        Task<RestaurantDto> GetRestaurantWithIdAsync(string Id);
Makes sense to me. I think that using a RestaurantEntity to interact with the database might be better. Maybe something we could address in a service layer PR.

2017-07-06 17:58 UTC, TNagaraja commented on wfl/Database/MongoDBManager.cs
> +        public async Task<bool> CheckRestaurantIdAsync(string id)
If I attempt to get by an invalid Id, it doesn't return null - it throws an error saying `sequence contains no elements`.

2017-07-10 19:36 UTC, enricoferrari requested changes

2017-07-10 19:36 UTC, enricoferrari commented on wfl/Database/MongoDBManager.cs
> +                Name = r.Name
Do we need to also update the MenuLink here? Would this effectively wipe out the MenuLink?

2017-07-10 19:43 UTC, TNagaraja commented on wfl/Database/MongoDBManager.cs
> +                Name = r.Name
I'll add this in.

2017-07-10 19:49 UTC, TNagaraja commented on wfl/Database/MongoDBManager.cs
> +                Name = r.Name
Changed in latest code

2017-07-11 12:58 UTC, enricoferrari commented on wfl/Database/MongoDBManager.cs
> +                Name = r.Name
You only changed the Insert method.

2017-07-11 13:34 UTC, jspringer2020 commented on wfl/Models/RestaurantDto.cs
> +        public Uri MenuLink { get; set; }
What does this actually end up saving in mongo?? When saving does it just `.ToString()`?

2017-07-11 14:45 UTC, TNagaraja commented on wfl/Database/MongoDBManager.cs
> +                Name = r.Name
Thanks. Should be fixed now.

2017-07-11 14:46 UTC, TNagaraja commented on wfl/Models/RestaurantDto.cs
> +        public Uri MenuLink { get; set; }
Yes, it just stores a string.

2017-07-11 14:47 UTC, enricoferrari approved these changes

2017-07-11 15:00 UTC, JChapman202 approved these changes

2017-07-11 15:00 UTC, merged