Delete Menu Selection
Symphono/wfl pull request #43
Opened 2017-07-18 20:14 UTC by TNagaraja

Issue #35

2017-07-21 16:56 UTC, jspringer2020 requested changes
One small change and a question about storage of documents.

- [ ] Update MenuSelectionsController to use a RoutePrefix attribute

2017-07-21 16:56 UTC, jspringer2020 commented on wfl/Controllers/MenuSelectionsController.cs
> +        [Route("api/menu-selection/{id}")]
We should try to use `RoutePrefix` so that the routes are all similar, unless there is a particular reason why we need to break that pattern.

2017-07-21 16:56 UTC, jspringer2020 commented on wfl/Database/IDBManager.cs
> +        Task<T> DeleteEntityByIdAsync<T>(string id) where T : IEntity;
I thought that we were storing the `MenuItems` as a child collection in the `FoodOrder` object? If that's the case, we have to remove the item from the child collection. Or are we moving away from document storage?

2017-07-21 17:40 UTC, TNagaraja commented on wfl/Database/IDBManager.cs
> +        Task<T> DeleteEntityByIdAsync<T>(string id) where T : IEntity;
I'm in the process of fixing this one currently. Going to stop storing MenuSelection objects directly into the db.

2017-07-21 20:03 UTC, enricoferrari requested changes
After the change to FoodOrderId in MenuSelection is finished and the RoutePrefix changes are finished  this looks good to me.

2017-07-24 14:32 UTC, TNagaraja commented on wfl/Controllers/MenuSelectionsController.cs
> +        [Route("api/menu-selection/{id}")]
I'll include this change.

2017-07-25 17:00 UTC, TNagaraja commented
Updated MenuSelectionsController to use a RoutePrefix attribute

2017-07-27 12:59 UTC, enricoferrari requested changes

2017-07-27 12:59 UTC, enricoferrari commented on wfl/Controllers/MenuSelectionsController.cs
> +        public async Task<IHttpActionResult> DeleteByIdAsync([FromUri] string foodOrderId, [FromUri] int index)
see my comment in the submit menu selection PR (where the MenuSelection model is defined) but I think this property `index` is problematic and needs to be replaced with an id.

2017-07-27 15:42 UTC, TNagaraja commented on wfl/Controllers/MenuSelectionsController.cs
> +        public async Task<IHttpActionResult> DeleteByIdAsync([FromUri] string foodOrderId, [FromUri] int index)
Changed in updated code.

2017-07-27 18:10 UTC, enricoferrari approved these changes

2017-07-31 19:13 UTC, jspringer2020 approved these changes
Looks good.

2017-08-02 12:50 UTC, JChapman202 requested changes
This looks good and is very straight forward.  I would just change the one implementation of how we're removing the item from the collection to use the same collection instead of an entirely new one.

2017-08-02 12:50 UTC, JChapman202 commented on wfl/Controllers/MenuSelectionsController.cs
> +            order.MenuSelections = order.MenuSelections.Where(x => x.Id != selectionId).ToList();
While this code will work to remove the menu selection in question, I think it'll make sense for us to look at making these changes with more minimal effort.  Even though for this application, we will never have an issue with scalability, it's still a good concept to be aware of.  In this case we could have simply removed a menu selection from the existing collection and saved the same object.  However, instead we are creating an entirely new collection, assigning that new collection to the object and then throwing the old one away.  I would recommend simply removing the item from the list and saving.

2017-08-02 12:50 UTC, JChapman202 commented on wfl/Models/FoodOrder.cs
> +                for(int i = 0; i < MenuSelections.Count; i++)
why did we need to make this change?

2017-08-02 17:36 UTC, TNagaraja commented on wfl/Controllers/MenuSelectionsController.cs
> +            order.MenuSelections = order.MenuSelections.Where(x => x.Id != selectionId).ToList();
Makes sense. I'll add this change in.

2017-08-02 17:37 UTC, TNagaraja commented on wfl/Models/FoodOrder.cs
> +                for(int i = 0; i < MenuSelections.Count; i++)
This change is not necessary. I had changed this earlier when I was updating the index of each menu selection. I'll change it back.

2017-08-03 15:50 UTC, merged