Complete food order
Symphono/wfl pull request #52
Opened 2017-07-31 18:44 UTC by TNagaraja

Issue #47

2017-07-31 18:56 UTC, enricoferrari requested changes

2017-07-31 18:56 UTC, enricoferrari commented on wfl/Models/EntityStatus.cs
>          public enum Status
I don't foresee this status being a generic thing. So I would name it specific to orders. I would be curious to ear others opinions on this but what do you guys think of defining the enum inside the FoodOrder vs in it's own top level file?

2017-07-31 18:56 UTC, enricoferrari commented on wfl/Controllers/FoodOrdersController.cs
> +            if (order.Status != EntityStatus.Status.Active)
you probably also want to null check order here

2017-07-31 19:03 UTC, TNagaraja commented on wfl/Controllers/FoodOrdersController.cs
> +            if (order.Status != EntityStatus.Status.Active)
Changed in latest code

2017-08-01 16:38 UTC, TNagaraja commented on wfl/Models/EntityStatus.cs
>          public enum Status
I'll move the status inside the FoodOrder class.

2017-08-01 17:17 UTC, enricoferrari commented on wfl/Controllers/FoodOrdersController.cs
> +        public async Task<IHttpActionResult> CompleteAsync([FromUri] string id)
I think @jspringer2020 mentioned this in another PR, but we could follow suit here and make this a generic controller method to set the status. The interesting part comes in the profile. There you advertise certain actions based on what the current status is. So IF an orders status is `Active` the profile will show a `complete` action. That action will call this method with the status `Completed`.

2017-08-01 17:27 UTC, TNagaraja commented on wfl/Controllers/FoodOrdersController.cs
> +        public async Task<IHttpActionResult> CompleteAsync([FromUri] string id)
I was in the process of making this change - should be up soon.

2017-08-01 18:43 UTC, TNagaraja commented on wfl/Controllers/FoodOrdersController.cs
> +        public async Task<IHttpActionResult> CompleteAsync([FromUri] string id)
Changed now.

2017-08-01 19:14 UTC, enricoferrari approved these changes

2017-08-08 15:09 UTC, jspringer2020 approved these changes
Looks good. This is a good starting point as we talked IRL yesterday. Longer term we would likely use a validation framework to handle a lot of this for us.

2017-08-08 15:09 UTC, merged